input.onLogoEvent(TouchButtonEvent.LongPressed, function () {
    motor.motorStopAll()
    music._playDefaultBackground(music.builtInPlayableMelody(Melodies.PowerUp), music.PlaybackMode.InBackground)
    basic.showIcon(IconNames.Target)
    motor.MotorRun(motor.Motors.M1, motor.Dir.CW, 255)
    motor.MotorRun(motor.Motors.M2, motor.Dir.CW, 255)
    motor.MotorRun(motor.Motors.M3, motor.Dir.CW, 255)
    motor.MotorRun(motor.Motors.M4, motor.Dir.CW, 255)
})
input.onButtonPressed(Button.A, function () {
    motor.motorStopAll()
    music.play(music.builtinPlayableSoundEffect(soundExpression.happy), music.PlaybackMode.InBackground)
    basic.showIcon(IconNames.Yes)
    motor.MotorRun(motor.Motors.M1, motor.Dir.CW, 50)
    motor.MotorRun(motor.Motors.M2, motor.Dir.CW, 50)
    motor.MotorRun(motor.Motors.M3, motor.Dir.CW, 50)
    motor.MotorRun(motor.Motors.M4, motor.Dir.CW, 50)
})
bluetooth.onUartDataReceived(serial.delimiters(Delimiters.Hash), function () {
    cmd = bluetooth.uartReadUntil("#")
    if (cmd == "F") {
        basic.showString("F")
        motor.MotorRun(motor.Motors.M1, motor.Dir.CW, 120)
        motor.MotorRun(motor.Motors.M2, motor.Dir.CW, 120)
        motor.MotorRun(motor.Motors.M3, motor.Dir.CW, 120)
        motor.MotorRun(motor.Motors.M4, motor.Dir.CW, 120)
    } else if (cmd == "B") {
        basic.showString("B")
        motor.MotorRun(motor.Motors.M1, motor.Dir.CCW, 120)
        motor.MotorRun(motor.Motors.M2, motor.Dir.CCW, 120)
        motor.MotorRun(motor.Motors.M3, motor.Dir.CCW, 120)
        motor.MotorRun(motor.Motors.M4, motor.Dir.CCW, 120)
    } else if (cmd == "S") {
        basic.showString("S")
        motor.motorStop(motor.Motors.M1)
        motor.motorStop(motor.Motors.M2)
        motor.motorStop(motor.Motors.M3)
        motor.motorStop(motor.Motors.M4)
    } else if (cmd == "L") {
        basic.showString("L")
        motor.motorStopAll()
        motor.MotorRun(motor.Motors.M1, motor.Dir.CW, 120)
        motor.MotorRun(motor.Motors.M2, motor.Dir.CW, 120)
    } else if (cmd == "R") {
        basic.showString("R")
        motor.motorStopAll()
        motor.MotorRun(motor.Motors.M3, motor.Dir.CW, 120)
        motor.MotorRun(motor.Motors.M4, motor.Dir.CW, 120)
    }
})
input.onButtonPressed(Button.B, function () {
    basic.showIcon(IconNames.No)
    motor.motorStopAll()
    music.play(music.builtinPlayableSoundEffect(soundExpression.sad), music.PlaybackMode.InBackground)
})
input.onLogoEvent(TouchButtonEvent.Touched, function () {
    motor.motorStopAll()
    music.play(music.builtinPlayableSoundEffect(soundExpression.slide), music.PlaybackMode.InBackground)
    basic.showIcon(IconNames.Happy)
    motor.MotorRun(motor.Motors.M1, motor.Dir.CW, 100)
    motor.MotorRun(motor.Motors.M2, motor.Dir.CW, 100)
    motor.MotorRun(motor.Motors.M3, motor.Dir.CW, 100)
    motor.MotorRun(motor.Motors.M4, motor.Dir.CW, 100)
})
let cmd = ""
motor.motorStopAll()
music.setVolume(255)
bluetooth.startUartService()
music.play(music.builtinPlayableSoundEffect(soundExpression.hello), music.PlaybackMode.InBackground)
basic.showString("Pizza")
basic.showIcon(IconNames.Heart)
